[package]
name = "arbitrage-system"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
prost = "0.12.6"
data-encoding = "2.9.0"
futures-util = "0.3.31"
hex = "0.4.3"
hmac = "0.12.1"
json = "0.12.4"
reqwest = "0.12.23"
sha2 = "0.10.9"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
tokio-tungstenite = { version = "0.28.0",  features = ["native-tls"]}
rand = "0.8"
md-5 = "0.10.6"
hex-literal = "1.1.0"
base64 = "0.22.1"
uuid = { version = "1.18.1", features = ["v4"] }
ring = "0.17.14"
chrono = "0.4"
urlencoding = "2.1"
dashmap = "6.1.0"
flate2 = "1.1.8"
dotenv = "0.15.0"


[build-dependencies]
prost-build = "0.12"

