use crate::config::{
    get_map,
    parameters::{ERROR_CODE, RESET_CODE},
};

#[derive(Debug, Clone)]
pub struct NetworkConfig {
    pub name: String,
    pub full_name: String,
    pub coin_name: String,
    pub withdraw_fee: Option<f64>,
    pub contract_address: Option<String>,
    pub memo: Option<String>,
    pub deposit_address: Option<String>,
}

pub enum NetworkType {
    Bitcoin,
    Ethereum,
    BinanceSmartChain,
    Solana,
    Sui,
    Stacks,
    Mina,
    Vanar,
    MultiversX,
    Rootstock,
    Scroll,
    Ton,
    Icon,
    Polygon,
    Harmony,
    ZkLinkNova,
    Base,
    Hemi,
    GunzNetwork,
    Avalanche,
    Arbitrum,
    WorldChain,
    Optimism,
    Flux,
    Celestia,
    Metis,
    Linea,
    Iost,
    Coti,
    Neo,
    Moonbeam,
    Chiliz,
    Bifrost,
    Dydx,
    Nero,
    Decred,
    Tron,
    Ontology,
    Dash,
    Mango,
    Story,
    Cyber,
    Eclipse,
    Gravity,
    Om,
    Viction,
    Verge,
    Initia,
    Babylon,
    QuarkChain,
    BitLayer,
    AssetHubKusama,
    Terra,
    TerraClassic,
    ZeroG,
    Bittensor,
    Bera,
    Celo,
    Endurance,
    Movement,
    Kusama,
    Plume,
    Xrp,
    ZkSync,
    Metal,
    Cardano,
    Dymension,
    Axelar,
    Moonriver,
    Bob,
    Lumia,
    Iota,
    Ronin,
    BounceBit,
    Immutable,
    Fantom,
    Enjin,
    Band,
}

#[derive(Debug, Clone)]
pub enum Network {
    Bitcoin(NetworkConfig),
    Ethereum(NetworkConfig),
    BinanceSmartChain(NetworkConfig),
    Solana(NetworkConfig),
    Sui(NetworkConfig),
    Stacks(NetworkConfig),
    Mina(NetworkConfig),
    Vanar(NetworkConfig),
    MultiversX(NetworkConfig),
    Rootstock(NetworkConfig),
    Scroll(NetworkConfig),
    Ton(NetworkConfig),
    Icon(NetworkConfig),
    Polygon(NetworkConfig),
    Harmony(NetworkConfig),
    ZkLinkNova(NetworkConfig),
    Base(NetworkConfig),
    Hemi(NetworkConfig),
    GunzNetwork(NetworkConfig),
    Avalanche(NetworkConfig),
    Arbitrum(NetworkConfig),
    WorldChain(NetworkConfig),
    Optimism(NetworkConfig),
    Flux(NetworkConfig),
    Celestia(NetworkConfig),
    Metis(NetworkConfig),
    Linea(NetworkConfig),
    Iost(NetworkConfig),
    Coti(NetworkConfig),
    Neo(NetworkConfig),
    Moonbeam(NetworkConfig),
    Chiliz(NetworkConfig),
    Bifrost(NetworkConfig),
    Dydx(NetworkConfig),
    Nero(NetworkConfig),
    Decred(NetworkConfig),
    Tron(NetworkConfig),
    Ontology(NetworkConfig),
    Dash(NetworkConfig),
    Mango(NetworkConfig),
    Story(NetworkConfig),
    Cyber(NetworkConfig),
    Eclipse(NetworkConfig),
    Gravity(NetworkConfig),
    Om(NetworkConfig),
    Viction(NetworkConfig),
    Verge(NetworkConfig),
    Initia(NetworkConfig),
    Babylon(NetworkConfig),
    QuarkChain(NetworkConfig),
    BitLayer(NetworkConfig),
    AssetHubKusama(NetworkConfig),
    Terra(NetworkConfig),
    TerraClassic(NetworkConfig),
    ZeroG(NetworkConfig),
    Bittensor(NetworkConfig),
    Bera(NetworkConfig),
    Celo(NetworkConfig),
    Endurance(NetworkConfig),
    Movement(NetworkConfig),
    Kusama(NetworkConfig),
    Plume(NetworkConfig),
    Xrp(NetworkConfig),
    ZkSync(NetworkConfig),
    Metal(NetworkConfig),
    Cardano(NetworkConfig),
    Dymension(NetworkConfig),
    Axelar(NetworkConfig),
    Moonriver(NetworkConfig),
    Bob(NetworkConfig),
    Lumia(NetworkConfig),
    Iota(NetworkConfig),
    Ronin(NetworkConfig),
    BounceBit(NetworkConfig),
    Immutable(NetworkConfig),
    Fantom(NetworkConfig),
    Enjin(NetworkConfig),
    Band(NetworkConfig),
}

impl Network {
    pub fn parse(name: String, full_name: String, coin_name: String) -> Option<Self> {
        let config = NetworkConfig {
            name,
            full_name,
            coin_name,
            withdraw_fee: None,
            contract_address: None,
            memo: None,
            deposit_address: None,
        };
        let mapped = Self::get_network_type(&config.name)
            .or_else(|| Network::get_network_type(&config.full_name));
        match mapped {
            Some(network_type) => match network_type {
                NetworkType::Bitcoin => Some(Self::Bitcoin(config)),
                NetworkType::Ethereum => Some(Self::Ethereum(config)),
                NetworkType::BinanceSmartChain => Some(Self::BinanceSmartChain(config)),
                NetworkType::Solana => Some(Self::Solana(config)),
                NetworkType::Sui => Some(Self::Sui(config)),
                NetworkType::Stacks => Some(Self::Stacks(config)),
                NetworkType::Mina => Some(Self::Mina(config)),
                NetworkType::Vanar => Some(Self::Vanar(config)),
                NetworkType::MultiversX => Some(Self::MultiversX(config)),
                NetworkType::Rootstock => Some(Self::Rootstock(config)),
                NetworkType::Scroll => Some(Self::Scroll(config)),
                NetworkType::Ton => Some(Self::Ton(config)),
                NetworkType::Icon => Some(Self::Icon(config)),
                NetworkType::Polygon => Some(Self::Polygon(config)),
                NetworkType::Harmony => Some(Self::Harmony(config)),
                NetworkType::ZkLinkNova => Some(Self::ZkLinkNova(config)),
                NetworkType::Base => Some(Self::Base(config)),
                NetworkType::Hemi => Some(Self::Hemi(config)),
                NetworkType::GunzNetwork => Some(Self::GunzNetwork(config)),
                NetworkType::Avalanche => Some(Self::Avalanche(config)),
                NetworkType::Arbitrum => Some(Self::Arbitrum(config)),
                NetworkType::WorldChain => Some(Self::WorldChain(config)),
                NetworkType::Optimism => Some(Self::Optimism(config)),
                NetworkType::Flux => Some(Self::Flux(config)),
                NetworkType::Celestia => Some(Self::Celestia(config)),
                NetworkType::Metis => Some(Self::Metis(config)),
                NetworkType::Linea => Some(Self::Linea(config)),
                NetworkType::Iost => Some(Self::Iost(config)),
                NetworkType::Coti => Some(Self::Coti(config)),
                NetworkType::Neo => Some(Self::Neo(config)),
                NetworkType::Moonbeam => Some(Self::Moonbeam(config)),
                NetworkType::Chiliz => Some(Self::Chiliz(config)),
                NetworkType::Bifrost => Some(Self::Bifrost(config)),
                NetworkType::Dydx => Some(Self::Dydx(config)),
                NetworkType::Nero => Some(Self::Nero(config)),
                NetworkType::Decred => Some(Self::Decred(config)),
                NetworkType::Tron => Some(Self::Tron(config)),
                NetworkType::Ontology => Some(Self::Ontology(config)),
                NetworkType::Dash => Some(Self::Dash(config)),
                NetworkType::Mango => Some(Self::Mango(config)),
                NetworkType::Story => Some(Self::Story(config)),
                NetworkType::Cyber => Some(Self::Cyber(config)),
                NetworkType::Eclipse => Some(Self::Eclipse(config)),
                NetworkType::Gravity => Some(Self::Gravity(config)),
                NetworkType::Om => Some(Self::Om(config)),
                NetworkType::Viction => Some(Self::Viction(config)),
                NetworkType::Verge => Some(Self::Verge(config)),
                NetworkType::Initia => Some(Self::Initia(config)),
                NetworkType::Babylon => Some(Self::Babylon(config)),
                NetworkType::QuarkChain => Some(Self::QuarkChain(config)),
                NetworkType::BitLayer => Some(Self::BitLayer(config)),
                NetworkType::AssetHubKusama => Some(Self::AssetHubKusama(config)),
                NetworkType::Terra => Some(Self::Terra(config)),
                NetworkType::TerraClassic => Some(Self::TerraClassic(config)),
                NetworkType::ZeroG => Some(Self::ZeroG(config)),
                NetworkType::Bittensor => Some(Self::Bittensor(config)),
                NetworkType::Bera => Some(Self::Bera(config)),
                NetworkType::Celo => Some(Self::Celo(config)),
                NetworkType::Endurance => Some(Self::Endurance(config)),
                NetworkType::Movement => Some(Self::Movement(config)),
                NetworkType::Kusama => Some(Self::Kusama(config)),
                NetworkType::Plume => Some(Self::Plume(config)),
                NetworkType::Xrp => Some(Self::Xrp(config)),
                NetworkType::ZkSync => Some(Self::ZkSync(config)),
                NetworkType::Metal => Some(Self::Metal(config)),
                NetworkType::Cardano => Some(Self::Cardano(config)),
                NetworkType::Dymension => Some(Self::Dymension(config)),
                NetworkType::Axelar => Some(Self::Axelar(config)),
                NetworkType::Moonriver => Some(Self::Moonriver(config)),
                NetworkType::Bob => Some(Self::Bob(config)),
                NetworkType::Lumia => Some(Self::Lumia(config)),
                NetworkType::Iota => Some(Self::Iota(config)),
                NetworkType::Ronin => Some(Self::Ronin(config)),
                NetworkType::BounceBit => Some(Self::BounceBit(config)),
                NetworkType::Immutable => Some(Self::Immutable(config)),
                NetworkType::Fantom => Some(Self::Fantom(config)),
                NetworkType::Enjin => Some(Self::Enjin(config)),
                NetworkType::Band => Some(Self::Band(config)),
            },

            None => {
                println!(
                    "{ERROR_CODE}[ERROR] Не удалось распознать сеть name: {} full_name: {}{RESET_CODE}",
                    config.name, config.full_name
                );
                None
            }
        }
    }
    fn get_network_type(name: &str) -> Option<&NetworkType> {
        get_map().get(&*name.to_uppercase())
    }
    pub fn set_deposit_addresss(&mut self, address: String) -> &Self {
        self.mut_config().deposit_address = Some(address);
        self
    }
    pub fn set_memo(&mut self, memo: String) -> &Self {
        self.mut_config().memo = Some(memo);
        self
    }
    pub fn set_withdraw_fee(&mut self, fee: f64) -> &Self {
        self.mut_config().withdraw_fee = Some(fee);
        self
    }
    pub fn set_contract(&mut self, address: String) -> &Self {
        self.mut_config().contract_address = Some(address);
        self
    }
    fn mut_config(&mut self) -> &mut NetworkConfig {
        match self {
            Self::Bitcoin(cfg) => cfg,
            Self::Ethereum(cfg) => cfg,
            Self::BinanceSmartChain(cfg) => cfg,
            Self::Solana(cfg) => cfg,
            Self::Sui(cfg) => cfg,
            Self::Stacks(cfg) => cfg,
            Self::Mina(cfg) => cfg,
            Self::Vanar(cfg) => cfg,
            Self::MultiversX(cfg) => cfg,
            Self::Rootstock(cfg) => cfg,
            Self::Scroll(cfg) => cfg,
            Self::Ton(cfg) => cfg,
            Self::Icon(cfg) => cfg,
            Self::Polygon(cfg) => cfg,
            Self::Harmony(cfg) => cfg,
            Self::ZkLinkNova(cfg) => cfg,
            Self::Base(cfg) => cfg,
            Self::Hemi(cfg) => cfg,
            Self::GunzNetwork(cfg) => cfg,
            Self::Avalanche(cfg) => cfg,
            Self::Arbitrum(cfg) => cfg,
            Self::WorldChain(cfg) => cfg,
            Self::Optimism(cfg) => cfg,
            Self::Flux(cfg) => cfg,
            Self::Celestia(cfg) => cfg,
            Self::Metis(cfg) => cfg,
            Self::Linea(cfg) => cfg,
            Self::Iost(cfg) => cfg,
            Self::Coti(cfg) => cfg,
            Self::Neo(cfg) => cfg,
            Self::Moonbeam(cfg) => cfg,
            Self::Chiliz(cfg) => cfg,
            Self::Bifrost(cfg) => cfg,
            Self::Dydx(cfg) => cfg,
            Self::Nero(cfg) => cfg,
            Self::Decred(cfg) => cfg,
            Self::Tron(cfg) => cfg,
            Self::Ontology(cfg) => cfg,
            Self::Dash(cfg) => cfg,
            Self::Mango(cfg) => cfg,
            Self::Story(cfg) => cfg,
            Self::Cyber(cfg) => cfg,
            Self::Eclipse(cfg) => cfg,
            Self::Gravity(cfg) => cfg,
            Self::Om(cfg) => cfg,
            Self::Viction(cfg) => cfg,
            Self::Verge(cfg) => cfg,
            Self::Initia(cfg) => cfg,
            Self::Babylon(cfg) => cfg,
            Self::QuarkChain(cfg) => cfg,
            Self::BitLayer(cfg) => cfg,
            Self::AssetHubKusama(cfg) => cfg,
            Self::Terra(cfg) => cfg,
            Self::TerraClassic(cfg) => cfg,
            Self::ZeroG(cfg) => cfg,
            Self::Bittensor(cfg) => cfg,
            Self::Bera(cfg) => cfg,
            Self::Celo(cfg) => cfg,
            Self::Endurance(cfg) => cfg,
            Self::Movement(cfg) => cfg,
            Self::Kusama(cfg) => cfg,
            Self::Plume(cfg) => cfg,
            Self::Xrp(cfg) => cfg,
            Self::ZkSync(cfg) => cfg,
            Self::Metal(cfg) => cfg,
            Self::Cardano(cfg) => cfg,
            Self::Dymension(cfg) => cfg,
            Self::Axelar(cfg) => cfg,
            Self::Moonriver(cfg) => cfg,
            Self::Bob(cfg) => cfg,
            Self::Lumia(cfg) => cfg,
            Self::Iota(cfg) => cfg,
            Self::Ronin(cfg) => cfg,
            Self::BounceBit(cfg) => cfg,
            Self::Immutable(cfg) => cfg,
            Self::Fantom(cfg) => cfg,
            Self::Enjin(cfg) => cfg,
            Self::Band(cfg) => cfg,
        }
    }

    pub fn create_test() -> Network {
        Network::Bitcoin(NetworkConfig {
            name: "TestNet".to_string(),
            full_name: "TestNetwork".to_string(),
            coin_name: "TestNet".to_string(),
            withdraw_fee: None,
            contract_address: None,
            memo: None,
            deposit_address: None,
        })
    }
}
