use crate::config::{
    get_map,
    parameters::{ERROR_CODE, RESET_CODE},
};

#[derive(Debug, Clone)]
pub struct NetworkConfig {
    pub name: String,
    pub full_name: String,
    pub coin_name: String,
    pub withdraw_fee: Option<f64>,
    pub contract_address: Option<String>,
    pub memo: Option<String>,
    pub deposit_address: Option<String>,
}

pub enum NetworkType {
    Bitcoin,
    Ethereum,
    BinanceSmartChain,
    Solana,
    Sui,
    Stacks,
    Mina,
    Vanar,
    MultiversX,
    Rootstock,
    Scroll,
    Ton,
    Icon,
    Polygon,
    Harmony,
    ZkLinkNova,
    Base,
    Hemi,
    GunzNetwork,
    Avalanche,
    Arbitrum,
    WorldChain,
    Optimism,
    Flux,
    Celestia,
    Metis,
    Linea,
    Iost,
    Coti,
    Neo,
    Moonbeam,
    Chiliz,
    Bifrost,
    Dydx,
    Nero,
    Decred,
    Tron,
    Ontology,
    Dash,
    Mango,
    Story,
    Cyber,
    Eclipse,
    Gravity,

    Viction,
    Verge,
    Initia,
    Babylon,
    QuarkChain,
    BitLayer,
    AssetHubKusama,
    Terra,
    TerraClassic,
    ZeroG,
    Bittensor,
    Bera,
    Celo,
    Endurance,
    Movement,
    Kusama,
    Plume,
    Xrp,
    ZkSync,
    Metal,
    Cardano,
    Dymension,
    Axelar,
    Moonriver,
    Bob,
    Lumia,
    Iota,
    Ronin,
    BounceBit,
    Immutable,
    Fantom,
    Enjin,
    Band,
    Sei,
    Litecoin,
    Dogecoin,
    Mantle,
    Starknet,
    Morph,
    ArbitrumNova,
    Manta,
    Near,
    Lightning,
    Kcc,
    BitcoinSegWit,
    Fogo,
    Frax,
    Siacoin,
    VeChain,
    Theta,
    FetchAi,
    Arweave,
    Oasis,
    Cosmos,
    Fraxtal,
    Ravencoin,
    AssetHubPolkadot,
    Hedera,
    Algorand,
    Conflux,
    Init,
    Stellar,
    DigiByte,
    Nano,
    ECash,
    Syscoin,
    Kava,
    IoTeX,
    InternetComputer,
    Acala,
    FitFi,
    Stable,
    Wemix,
    Filecoin,
    Waves,
    Neutron,
    Merlin,
    Aurora,
    Nem,
    Skale,
    Solar,
    Nillion,
    Elastos,
    HyperEVM,
    Klaytn,
    Plasma,
    Zilliqa,
    SyscoinRollux,
    Injective,
    Thorchain,
    Sapphire,
    Zcash,
    Klever,
    Wax,
    Kaia,
    MantaAtlantic,
    ZigChain,
    Aptos,
    Chromia,
    Tanssi,
    MilkyWay,
    Flow,
    Qtum,
    VSystems,
    Beldex,
    Secret,
    Astar,
    Supra,
    Canton,
    Oort,
    Matrix,
    Xion,
    Xfi,
    U2U,
    Mintlayer,
    Xai,
    SmartChain,
    Meter,
    MeterGovernance,
    MapProtocol,
    Beam,
    Bitgert,
    Hype,
    Pivx,
    EthereumPoW,
    Oraichain,
    Namada,
    MantraChain,
    Shibarium,
    Tezos,
    Etherlink,
    Zircuit,
    Telos,
    UnicornUltraSolaris,
    Analog,
    Vana,
    Swell,
    Aleo,
    Flare,
    Camp,
    Venom,
    Bitshares,
    Hydragon,
    Sonic,
    NewChain,
    Casper,
    Hive,
    Octa,
    Shentu,
    Lukso,
    Nibiru,
    Osmosis,
    Tbc,
    Electroneum,
    Iron,
    Fio,
    Radix,
    Cronos,
    Xna,
    Fractal,
    Ergo,
    Fuse,
    Vaulta,
    Shardeum,
    HashKey,
    StaFi,
    Peaq,
    Steem,
    Sophon,
    Polymesh,
    Numbers,
    Kaspa,
    Constellation,
    T3rn,
    BitcoinSV,
    Maverick,
    Monero,
    Mon,
    Ultima,
    GraphLinq,
    Irisnet,
    Stratis,
    Pocket,
    Aelf,
    Ark,
    Akash,
    Core,
    XLayer,
    Allora,
    Emyria,
    EthereumClassic,
    Proton,
    Avail,
    Kub,
    ABCore,
    Humanode,
    Dynex,
    Saga,
    Oasys,
    Wanchain,
    Zelcash,
    Luckycoin,
    Lamina1,
    ZkVerify,
    Nervos,
    Blast,
    AlephZero,
    Somnia,
}

#[derive(Debug, Clone)]
pub enum Network {
    Bitcoin(NetworkConfig),
    Ethereum(NetworkConfig),
    BinanceSmartChain(NetworkConfig),
    Solana(NetworkConfig),
    Sui(NetworkConfig),
    Stacks(NetworkConfig),
    Mina(NetworkConfig),
    Vanar(NetworkConfig),
    MultiversX(NetworkConfig),
    Rootstock(NetworkConfig),
    Scroll(NetworkConfig),
    Ton(NetworkConfig),
    Icon(NetworkConfig),
    Polygon(NetworkConfig),
    Harmony(NetworkConfig),
    ZkLinkNova(NetworkConfig),
    Base(NetworkConfig),
    Hemi(NetworkConfig),
    GunzNetwork(NetworkConfig),
    Avalanche(NetworkConfig),
    Arbitrum(NetworkConfig),
    WorldChain(NetworkConfig),
    Optimism(NetworkConfig),
    Flux(NetworkConfig),
    Celestia(NetworkConfig),
    Metis(NetworkConfig),
    Linea(NetworkConfig),
    Iost(NetworkConfig),
    Coti(NetworkConfig),
    Neo(NetworkConfig),
    Moonbeam(NetworkConfig),
    Chiliz(NetworkConfig),
    Bifrost(NetworkConfig),
    Dydx(NetworkConfig),
    Nero(NetworkConfig),
    Decred(NetworkConfig),
    Tron(NetworkConfig),
    Ontology(NetworkConfig),
    Dash(NetworkConfig),
    Mango(NetworkConfig),
    Story(NetworkConfig),
    Cyber(NetworkConfig),
    Eclipse(NetworkConfig),
    Gravity(NetworkConfig),
    Viction(NetworkConfig),
    Verge(NetworkConfig),
    Initia(NetworkConfig),
    Babylon(NetworkConfig),
    QuarkChain(NetworkConfig),
    BitLayer(NetworkConfig),
    AssetHubKusama(NetworkConfig),
    Terra(NetworkConfig),
    TerraClassic(NetworkConfig),
    ZeroG(NetworkConfig),
    Bittensor(NetworkConfig),
    Bera(NetworkConfig),
    Celo(NetworkConfig),
    Endurance(NetworkConfig),
    Movement(NetworkConfig),
    Kusama(NetworkConfig),
    Plume(NetworkConfig),
    Xrp(NetworkConfig),
    ZkSync(NetworkConfig),
    Metal(NetworkConfig),
    Cardano(NetworkConfig),
    Dymension(NetworkConfig),
    Axelar(NetworkConfig),
    Moonriver(NetworkConfig),
    Bob(NetworkConfig),
    Lumia(NetworkConfig),
    Iota(NetworkConfig),
    Ronin(NetworkConfig),
    BounceBit(NetworkConfig),
    Immutable(NetworkConfig),
    Fantom(NetworkConfig),
    Enjin(NetworkConfig),
    Band(NetworkConfig),
    Sei(NetworkConfig),
    Litecoin(NetworkConfig),
    Dogecoin(NetworkConfig),
    Mantle(NetworkConfig),
    Starknet(NetworkConfig),
    Morph(NetworkConfig),
    ArbitrumNova(NetworkConfig),
    Manta(NetworkConfig),
    Near(NetworkConfig),
    Lightning(NetworkConfig),
    Kcc(NetworkConfig),
    BitcoinSegWit(NetworkConfig),
    Fogo(NetworkConfig),
    Frax(NetworkConfig),
    Siacoin(NetworkConfig),
    VeChain(NetworkConfig),
    Theta(NetworkConfig),
    FetchAi(NetworkConfig),
    Arweave(NetworkConfig),
    Oasis(NetworkConfig),
    Cosmos(NetworkConfig),
    Fraxtal(NetworkConfig),
    Ravencoin(NetworkConfig),
    AssetHubPolkadot(NetworkConfig),
    Hedera(NetworkConfig),
    Algorand(NetworkConfig),
    Conflux(NetworkConfig),
    Init(NetworkConfig),
    Stellar(NetworkConfig),
    DigiByte(NetworkConfig),
    Nano(NetworkConfig),
    ECash(NetworkConfig),
    Syscoin(NetworkConfig),
    Kava(NetworkConfig),
    IoTeX(NetworkConfig),
    InternetComputer(NetworkConfig),
    Acala(NetworkConfig),
    FitFi(NetworkConfig),
    Stable(NetworkConfig),
    Wemix(NetworkConfig),
    Filecoin(NetworkConfig),
    Waves(NetworkConfig),
    Neutron(NetworkConfig),
    Merlin(NetworkConfig),
    Aurora(NetworkConfig),
    Nem(NetworkConfig),
    Skale(NetworkConfig),
    Solar(NetworkConfig),
    Nillion(NetworkConfig),
    Elastos(NetworkConfig),
    HyperEVM(NetworkConfig),
    Klaytn(NetworkConfig),
    Plasma(NetworkConfig),
    Zilliqa(NetworkConfig),
    SyscoinRollux(NetworkConfig),
    Injective(NetworkConfig),
    Thorchain(NetworkConfig),
    Sapphire(NetworkConfig),
    Zcash(NetworkConfig),
    Klever(NetworkConfig),
    Wax(NetworkConfig),
    Kaia(NetworkConfig),
    MantaAtlantic(NetworkConfig),
    ZigChain(NetworkConfig),
    Aptos(NetworkConfig),
    Chromia(NetworkConfig),
    Tanssi(NetworkConfig),
    MilkyWay(NetworkConfig),
    Flow(NetworkConfig),
    Qtum(NetworkConfig),
    VSystems(NetworkConfig),
    Beldex(NetworkConfig),
    Secret(NetworkConfig),
    Astar(NetworkConfig),
    Supra(NetworkConfig),
    Canton(NetworkConfig),
    Oort(NetworkConfig),
    Matrix(NetworkConfig),
    Xion(NetworkConfig),
    Xfi(NetworkConfig),
    U2U(NetworkConfig),
    Mintlayer(NetworkConfig),
    Xai(NetworkConfig),
    SmartChain(NetworkConfig),
    Meter(NetworkConfig),
    MeterGovernance(NetworkConfig),
    MapProtocol(NetworkConfig),
    Beam(NetworkConfig),
    Bitgert(NetworkConfig),
    Hype(NetworkConfig),
    Pivx(NetworkConfig),
    EthereumPoW(NetworkConfig),
    Oraichain(NetworkConfig),
    Namada(NetworkConfig),
    MantraChain(NetworkConfig),
    Shibarium(NetworkConfig),
    Tezos(NetworkConfig),
    Etherlink(NetworkConfig),
    Zircuit(NetworkConfig),
    Telos(NetworkConfig),
    UnicornUltraSolaris(NetworkConfig),
    Analog(NetworkConfig),
    Vana(NetworkConfig),
    Swell(NetworkConfig),
    Aleo(NetworkConfig),
    Flare(NetworkConfig),
    Camp(NetworkConfig),
    Venom(NetworkConfig),
    Bitshares(NetworkConfig),
    Hydragon(NetworkConfig),
    Sonic(NetworkConfig),
    NewChain(NetworkConfig),
    Casper(NetworkConfig),
    Hive(NetworkConfig),
    Octa(NetworkConfig),
    Shentu(NetworkConfig),
    Lukso(NetworkConfig),
    Nibiru(NetworkConfig),
    Osmosis(NetworkConfig),
    Tbc(NetworkConfig),
    Electroneum(NetworkConfig),
    Iron(NetworkConfig),
    Fio(NetworkConfig),
    Radix(NetworkConfig),
    Cronos(NetworkConfig),
    Xna(NetworkConfig),
    Fractal(NetworkConfig),
    Ergo(NetworkConfig),
    Fuse(NetworkConfig),
    Vaulta(NetworkConfig),
    Shardeum(NetworkConfig),
    HashKey(NetworkConfig),
    StaFi(NetworkConfig),
    Peaq(NetworkConfig),
    Steem(NetworkConfig),
    Sophon(NetworkConfig),
    Polymesh(NetworkConfig),
    Numbers(NetworkConfig),
    Kaspa(NetworkConfig),
    Constellation(NetworkConfig),
    T3rn(NetworkConfig),
    BitcoinSV(NetworkConfig),
    Maverick(NetworkConfig),
    Monero(NetworkConfig),
    Mon(NetworkConfig),
    Ultima(NetworkConfig),
    GraphLinq(NetworkConfig),
    Irisnet(NetworkConfig),
    Stratis(NetworkConfig),
    Pocket(NetworkConfig),
    Aelf(NetworkConfig),
    Ark(NetworkConfig),
    Akash(NetworkConfig),
    Core(NetworkConfig),
    XLayer(NetworkConfig),
    Allora(NetworkConfig),
    Emyria(NetworkConfig),
    EthereumClassic(NetworkConfig),
    Proton(NetworkConfig),
    Avail(NetworkConfig),
    Kub(NetworkConfig),
    ABCore(NetworkConfig),
    Humanode(NetworkConfig),
    Dynex(NetworkConfig),
    Saga(NetworkConfig),
    Oasys(NetworkConfig),
    Wanchain(NetworkConfig),
    Zelcash(NetworkConfig),
    Luckycoin(NetworkConfig),
    Lamina1(NetworkConfig),
    ZkVerify(NetworkConfig),
    Nervos(NetworkConfig),
    Blast(NetworkConfig),
    AlephZero(NetworkConfig),
    Somnia(NetworkConfig),
}

impl Network {
    pub fn parse(name: String, full_name: String, coin_name: String) -> Option<Self> {
        let config = NetworkConfig {
            name,
            full_name,
            coin_name,
            withdraw_fee: None,
            contract_address: None,
            memo: None,
            deposit_address: None,
        };
        let mapped = Self::get_network_type(&config.name)
            .or_else(|| Network::get_network_type(&config.full_name));
        match mapped {
            Some(network_type) => match network_type {
                NetworkType::Bitcoin => Some(Self::Bitcoin(config)),
                NetworkType::Ethereum => Some(Self::Ethereum(config)),
                NetworkType::BinanceSmartChain => Some(Self::BinanceSmartChain(config)),
                NetworkType::Solana => Some(Self::Solana(config)),
                NetworkType::Sui => Some(Self::Sui(config)),
                NetworkType::Stacks => Some(Self::Stacks(config)),
                NetworkType::Mina => Some(Self::Mina(config)),
                NetworkType::Vanar => Some(Self::Vanar(config)),
                NetworkType::MultiversX => Some(Self::MultiversX(config)),
                NetworkType::Rootstock => Some(Self::Rootstock(config)),
                NetworkType::Scroll => Some(Self::Scroll(config)),
                NetworkType::Ton => Some(Self::Ton(config)),
                NetworkType::Icon => Some(Self::Icon(config)),
                NetworkType::Polygon => Some(Self::Polygon(config)),
                NetworkType::Harmony => Some(Self::Harmony(config)),
                NetworkType::ZkLinkNova => Some(Self::ZkLinkNova(config)),
                NetworkType::Base => Some(Self::Base(config)),
                NetworkType::Hemi => Some(Self::Hemi(config)),
                NetworkType::GunzNetwork => Some(Self::GunzNetwork(config)),
                NetworkType::Avalanche => Some(Self::Avalanche(config)),
                NetworkType::Arbitrum => Some(Self::Arbitrum(config)),
                NetworkType::WorldChain => Some(Self::WorldChain(config)),
                NetworkType::Optimism => Some(Self::Optimism(config)),
                NetworkType::Flux => Some(Self::Flux(config)),
                NetworkType::Celestia => Some(Self::Celestia(config)),
                NetworkType::Metis => Some(Self::Metis(config)),
                NetworkType::Linea => Some(Self::Linea(config)),
                NetworkType::Iost => Some(Self::Iost(config)),
                NetworkType::Coti => Some(Self::Coti(config)),
                NetworkType::Neo => Some(Self::Neo(config)),
                NetworkType::Moonbeam => Some(Self::Moonbeam(config)),
                NetworkType::Chiliz => Some(Self::Chiliz(config)),
                NetworkType::Bifrost => Some(Self::Bifrost(config)),
                NetworkType::Dydx => Some(Self::Dydx(config)),
                NetworkType::Nero => Some(Self::Nero(config)),
                NetworkType::Decred => Some(Self::Decred(config)),
                NetworkType::Tron => Some(Self::Tron(config)),
                NetworkType::Ontology => Some(Self::Ontology(config)),
                NetworkType::Dash => Some(Self::Dash(config)),
                NetworkType::Mango => Some(Self::Mango(config)),
                NetworkType::Story => Some(Self::Story(config)),
                NetworkType::Cyber => Some(Self::Cyber(config)),
                NetworkType::Eclipse => Some(Self::Eclipse(config)),
                NetworkType::Gravity => Some(Self::Gravity(config)),
                NetworkType::Viction => Some(Self::Viction(config)),
                NetworkType::Verge => Some(Self::Verge(config)),
                NetworkType::Initia => Some(Self::Initia(config)),
                NetworkType::Babylon => Some(Self::Babylon(config)),
                NetworkType::QuarkChain => Some(Self::QuarkChain(config)),
                NetworkType::BitLayer => Some(Self::BitLayer(config)),
                NetworkType::AssetHubKusama => Some(Self::AssetHubKusama(config)),
                NetworkType::Terra => Some(Self::Terra(config)),
                NetworkType::TerraClassic => Some(Self::TerraClassic(config)),
                NetworkType::ZeroG => Some(Self::ZeroG(config)),
                NetworkType::Bittensor => Some(Self::Bittensor(config)),
                NetworkType::Bera => Some(Self::Bera(config)),
                NetworkType::Celo => Some(Self::Celo(config)),
                NetworkType::Endurance => Some(Self::Endurance(config)),
                NetworkType::Movement => Some(Self::Movement(config)),
                NetworkType::Kusama => Some(Self::Kusama(config)),
                NetworkType::Plume => Some(Self::Plume(config)),
                NetworkType::Xrp => Some(Self::Xrp(config)),
                NetworkType::ZkSync => Some(Self::ZkSync(config)),
                NetworkType::Metal => Some(Self::Metal(config)),
                NetworkType::Cardano => Some(Self::Cardano(config)),
                NetworkType::Dymension => Some(Self::Dymension(config)),
                NetworkType::Axelar => Some(Self::Axelar(config)),
                NetworkType::Moonriver => Some(Self::Moonriver(config)),
                NetworkType::Bob => Some(Self::Bob(config)),
                NetworkType::Lumia => Some(Self::Lumia(config)),
                NetworkType::Iota => Some(Self::Iota(config)),
                NetworkType::Ronin => Some(Self::Ronin(config)),
                NetworkType::BounceBit => Some(Self::BounceBit(config)),
                NetworkType::Immutable => Some(Self::Immutable(config)),
                NetworkType::Fantom => Some(Self::Fantom(config)),
                NetworkType::Enjin => Some(Self::Enjin(config)),
                NetworkType::Band => Some(Self::Band(config)),
                NetworkType::Sei => Some(Self::Sei(config)),
                NetworkType::Litecoin => Some(Self::Litecoin(config)),
                NetworkType::Dogecoin => Some(Self::Dogecoin(config)),
                NetworkType::Mantle => Some(Self::Mantle(config)),
                NetworkType::Starknet => Some(Self::Starknet(config)),
                NetworkType::Morph => Some(Self::Morph(config)),
                NetworkType::ArbitrumNova => Some(Self::ArbitrumNova(config)),
                NetworkType::Manta => Some(Self::Manta(config)),
                NetworkType::Near => Some(Self::Near(config)),
                NetworkType::Lightning => Some(Self::Lightning(config)),
                NetworkType::Kcc => Some(Self::Kcc(config)),
                NetworkType::BitcoinSegWit => Some(Self::BitcoinSegWit(config)),
                NetworkType::Fogo => Some(Self::Fogo(config)),
                NetworkType::Frax => Some(Self::Frax(config)),
                NetworkType::Siacoin => Some(Self::Siacoin(config)),
                NetworkType::VeChain => Some(Self::VeChain(config)),
                NetworkType::Theta => Some(Self::Theta(config)),
                NetworkType::FetchAi => Some(Self::FetchAi(config)),
                NetworkType::Arweave => Some(Self::Arweave(config)),
                NetworkType::Oasis => Some(Self::Oasis(config)),
                NetworkType::Cosmos => Some(Self::Cosmos(config)),
                NetworkType::Fraxtal => Some(Self::Fraxtal(config)),
                NetworkType::Ravencoin => Some(Self::Ravencoin(config)),
                NetworkType::AssetHubPolkadot => Some(Self::AssetHubPolkadot(config)),
                NetworkType::Hedera => Some(Self::Hedera(config)),
                NetworkType::Algorand => Some(Self::Algorand(config)),
                NetworkType::Conflux => Some(Self::Conflux(config)),
                NetworkType::Init => Some(Self::Init(config)),
                NetworkType::Stellar => Some(Self::Stellar(config)),
                NetworkType::DigiByte => Some(Self::DigiByte(config)),
                NetworkType::Nano => Some(Self::Nano(config)),
                NetworkType::ECash => Some(Self::ECash(config)),
                NetworkType::Syscoin => Some(Self::Syscoin(config)),
                NetworkType::Kava => Some(Self::Kava(config)),
                NetworkType::IoTeX => Some(Self::IoTeX(config)),
                NetworkType::InternetComputer => Some(Self::InternetComputer(config)),
                NetworkType::Acala => Some(Self::Acala(config)),
                NetworkType::FitFi => Some(Self::FitFi(config)),
                NetworkType::Stable => Some(Self::Stable(config)),
                NetworkType::Wemix => Some(Self::Wemix(config)),
                NetworkType::Filecoin => Some(Self::Filecoin(config)),
                NetworkType::Waves => Some(Self::Waves(config)),
                NetworkType::Neutron => Some(Self::Neutron(config)),
                NetworkType::Merlin => Some(Self::Merlin(config)),
                NetworkType::Aurora => Some(Self::Aurora(config)),
                NetworkType::Nem => Some(Self::Nem(config)),
                NetworkType::Skale => Some(Self::Skale(config)),
                NetworkType::Solar => Some(Self::Solar(config)),
                NetworkType::Nillion => Some(Self::Nillion(config)),
                NetworkType::Elastos => Some(Self::Elastos(config)),
                NetworkType::HyperEVM => Some(Self::HyperEVM(config)),
                NetworkType::Klaytn => Some(Self::Klaytn(config)),
                NetworkType::Plasma => Some(Self::Plasma(config)),
                NetworkType::Zilliqa => Some(Self::Zilliqa(config)),
                NetworkType::SyscoinRollux => Some(Self::SyscoinRollux(config)),
                NetworkType::Injective => Some(Self::Injective(config)),
                NetworkType::Thorchain => Some(Self::Thorchain(config)),
                NetworkType::Sapphire => Some(Self::Sapphire(config)),
                NetworkType::Zcash => Some(Self::Zcash(config)),
                NetworkType::Klever => Some(Self::Klever(config)),
                NetworkType::Wax => Some(Self::Wax(config)),
                NetworkType::Kaia => Some(Self::Kaia(config)),
                NetworkType::MantaAtlantic => Some(Self::MantaAtlantic(config)),
                NetworkType::ZigChain => Some(Self::ZigChain(config)),
                NetworkType::Aptos => Some(Self::Aptos(config)),
                NetworkType::Chromia => Some(Self::Chromia(config)),
                NetworkType::Tanssi => Some(Self::Tanssi(config)),
                NetworkType::MilkyWay => Some(Self::MilkyWay(config)),
                NetworkType::Flow => Some(Self::Flow(config)),
                NetworkType::Qtum => Some(Self::Qtum(config)),
                NetworkType::VSystems => Some(Self::VSystems(config)),
                NetworkType::Beldex => Some(Self::Beldex(config)),
                NetworkType::Secret => Some(Self::Secret(config)),
                NetworkType::Astar => Some(Self::Astar(config)),
                NetworkType::Supra => Some(Self::Supra(config)),
                NetworkType::Canton => Some(Self::Canton(config)),
                NetworkType::Oort => Some(Self::Oort(config)),
                NetworkType::Matrix => Some(Self::Matrix(config)),
                NetworkType::Xion => Some(Self::Xion(config)),
                NetworkType::Xfi => Some(Self::Xfi(config)),
                NetworkType::U2U => Some(Self::U2U(config)),
                NetworkType::Mintlayer => Some(Self::Mintlayer(config)),
                NetworkType::Xai => Some(Self::Xai(config)),
                NetworkType::SmartChain => Some(Self::SmartChain(config)),
                NetworkType::Meter => Some(Self::Meter(config)),
                NetworkType::MeterGovernance => Some(Self::MeterGovernance(config)),
                NetworkType::MapProtocol => Some(Self::MapProtocol(config)),
                NetworkType::Beam => Some(Self::Beam(config)),
                NetworkType::Bitgert => Some(Self::Bitgert(config)),
                NetworkType::Hype => Some(Self::Hype(config)),
                NetworkType::Pivx => Some(Self::Pivx(config)),
                NetworkType::EthereumPoW => Some(Self::EthereumPoW(config)),
                NetworkType::Oraichain => Some(Self::Oraichain(config)),
                NetworkType::Namada => Some(Self::Namada(config)),
                NetworkType::MantraChain => Some(Self::MantraChain(config)),
                NetworkType::Shibarium => Some(Self::Shibarium(config)),
                NetworkType::Tezos => Some(Self::Tezos(config)),
                NetworkType::Etherlink => Some(Self::Etherlink(config)),
                NetworkType::Zircuit => Some(Self::Zircuit(config)),
                NetworkType::Telos => Some(Self::Telos(config)),
                NetworkType::UnicornUltraSolaris => Some(Self::UnicornUltraSolaris(config)),
                NetworkType::Analog => Some(Self::Analog(config)),
                NetworkType::Vana => Some(Self::Vana(config)),
                NetworkType::Swell => Some(Self::Swell(config)),
                NetworkType::Aleo => Some(Self::Aleo(config)),
                NetworkType::Flare => Some(Self::Flare(config)),
                NetworkType::Camp => Some(Self::Camp(config)),
                NetworkType::Venom => Some(Self::Venom(config)),
                NetworkType::Bitshares => Some(Self::Bitshares(config)),
                NetworkType::Hydragon => Some(Self::Hydragon(config)),
                NetworkType::Sonic => Some(Self::Sonic(config)),
                NetworkType::NewChain => Some(Self::NewChain(config)),
                NetworkType::Casper => Some(Self::Casper(config)),
                NetworkType::Hive => Some(Self::Hive(config)),
                NetworkType::Octa => Some(Self::Octa(config)),
                NetworkType::Shentu => Some(Self::Shentu(config)),
                NetworkType::Lukso => Some(Self::Lukso(config)),
                NetworkType::Nibiru => Some(Self::Nibiru(config)),
                NetworkType::Osmosis => Some(Self::Osmosis(config)),
                NetworkType::Tbc => Some(Self::Tbc(config)),
                NetworkType::Electroneum => Some(Self::Electroneum(config)),
                NetworkType::Iron => Some(Self::Iron(config)),
                NetworkType::Fio => Some(Self::Fio(config)),
                NetworkType::Radix => Some(Self::Radix(config)),
                NetworkType::Cronos => Some(Self::Cronos(config)),
                NetworkType::Xna => Some(Self::Xna(config)),
                NetworkType::Fractal => Some(Self::Fractal(config)),
                NetworkType::Ergo => Some(Self::Ergo(config)),
                NetworkType::Fuse => Some(Self::Fuse(config)),
                NetworkType::Vaulta => Some(Self::Vaulta(config)),
                NetworkType::Shardeum => Some(Self::Shardeum(config)),
                NetworkType::HashKey => Some(Self::HashKey(config)),
                NetworkType::StaFi => Some(Self::StaFi(config)),
                NetworkType::Peaq => Some(Self::Peaq(config)),
                NetworkType::Steem => Some(Self::Steem(config)),
                NetworkType::Sophon => Some(Self::Sophon(config)),
                NetworkType::Polymesh => Some(Self::Polymesh(config)),
                NetworkType::Numbers => Some(Self::Numbers(config)),
                NetworkType::Kaspa => Some(Self::Kaspa(config)),
                NetworkType::Constellation => Some(Self::Constellation(config)),
                NetworkType::T3rn => Some(Self::T3rn(config)),
                NetworkType::BitcoinSV => Some(Self::BitcoinSV(config)),
                NetworkType::Maverick => Some(Self::Maverick(config)),
                NetworkType::Monero => Some(Self::Monero(config)),
                NetworkType::Mon => Some(Self::Mon(config)),
                NetworkType::Ultima => Some(Self::Ultima(config)),
                NetworkType::GraphLinq => Some(Self::GraphLinq(config)),
                NetworkType::Irisnet => Some(Self::Irisnet(config)),
                NetworkType::Stratis => Some(Self::Stratis(config)),
                NetworkType::Pocket => Some(Self::Pocket(config)),
                NetworkType::Aelf => Some(Self::Aelf(config)),
                NetworkType::Ark => Some(Self::Ark(config)),
                NetworkType::Akash => Some(Self::Akash(config)),
                NetworkType::Core => Some(Self::Core(config)),
                NetworkType::XLayer => Some(Self::XLayer(config)),
                NetworkType::Allora => Some(Self::Allora(config)),
                NetworkType::Emyria => Some(Self::Emyria(config)),
                NetworkType::EthereumClassic => Some(Self::EthereumClassic(config)),
                NetworkType::Proton => Some(Self::Proton(config)),
                NetworkType::Avail => Some(Self::Avail(config)),
                NetworkType::Kub => Some(Self::Kub(config)),
                NetworkType::ABCore => Some(Self::ABCore(config)),
                NetworkType::Humanode => Some(Self::Humanode(config)),
                NetworkType::Dynex => Some(Self::Dynex(config)),
                NetworkType::Saga => Some(Self::Saga(config)),
                NetworkType::Oasys => Some(Self::Oasys(config)),
                NetworkType::Wanchain => Some(Self::Wanchain(config)),
                NetworkType::Zelcash => Some(Self::Zelcash(config)),
                NetworkType::Luckycoin => Some(Self::Luckycoin(config)),
                NetworkType::Lamina1 => Some(Self::Lamina1(config)),
                NetworkType::ZkVerify => Some(Self::ZkVerify(config)),
                NetworkType::Nervos => Some(Self::Nervos(config)),
                NetworkType::Blast => Some(Self::Blast(config)),
                NetworkType::AlephZero => Some(Self::AlephZero(config)),
                NetworkType::Somnia => Some(Self::Somnia(config)),
            },

            None => {
                println!(
                    "{ERROR_CODE}[ERROR] Не удалось распознать сеть name: {} full_name: {}{RESET_CODE}",
                    config.name, config.full_name
                );
                None
            }
        }
    }
    fn get_network_type(name: &str) -> Option<&NetworkType> {
        get_map().get(&*name.to_uppercase())
    }
    pub fn set_deposit_addresss(&mut self, address: String) -> &Self {
        self.mut_config().deposit_address = Some(address);
        self
    }
    pub fn set_memo(&mut self, memo: String) -> &Self {
        self.mut_config().memo = Some(memo);
        self
    }
    pub fn set_withdraw_fee(&mut self, fee: f64) -> &Self {
        self.mut_config().withdraw_fee = Some(fee);
        self
    }
    pub fn set_contract(&mut self, address: String) -> &Self {
        self.mut_config().contract_address = Some(address);
        self
    }
    fn mut_config(&mut self) -> &mut NetworkConfig {
        match self {
            Self::Bitcoin(cfg) => cfg,
            Self::Ethereum(cfg) => cfg,
            Self::BinanceSmartChain(cfg) => cfg,
            Self::Solana(cfg) => cfg,
            Self::Sui(cfg) => cfg,
            Self::Stacks(cfg) => cfg,
            Self::Mina(cfg) => cfg,
            Self::Vanar(cfg) => cfg,
            Self::MultiversX(cfg) => cfg,
            Self::Rootstock(cfg) => cfg,
            Self::Scroll(cfg) => cfg,
            Self::Ton(cfg) => cfg,
            Self::Icon(cfg) => cfg,
            Self::Polygon(cfg) => cfg,
            Self::Harmony(cfg) => cfg,
            Self::ZkLinkNova(cfg) => cfg,
            Self::Base(cfg) => cfg,
            Self::Hemi(cfg) => cfg,
            Self::GunzNetwork(cfg) => cfg,
            Self::Avalanche(cfg) => cfg,
            Self::Arbitrum(cfg) => cfg,
            Self::WorldChain(cfg) => cfg,
            Self::Optimism(cfg) => cfg,
            Self::Flux(cfg) => cfg,
            Self::Celestia(cfg) => cfg,
            Self::Metis(cfg) => cfg,
            Self::Linea(cfg) => cfg,
            Self::Iost(cfg) => cfg,
            Self::Coti(cfg) => cfg,
            Self::Neo(cfg) => cfg,
            Self::Moonbeam(cfg) => cfg,
            Self::Chiliz(cfg) => cfg,
            Self::Bifrost(cfg) => cfg,
            Self::Dydx(cfg) => cfg,
            Self::Nero(cfg) => cfg,
            Self::Decred(cfg) => cfg,
            Self::Tron(cfg) => cfg,
            Self::Ontology(cfg) => cfg,
            Self::Dash(cfg) => cfg,
            Self::Mango(cfg) => cfg,
            Self::Story(cfg) => cfg,
            Self::Cyber(cfg) => cfg,
            Self::Eclipse(cfg) => cfg,
            Self::Gravity(cfg) => cfg,
            Self::Viction(cfg) => cfg,
            Self::Verge(cfg) => cfg,
            Self::Initia(cfg) => cfg,
            Self::Babylon(cfg) => cfg,
            Self::QuarkChain(cfg) => cfg,
            Self::BitLayer(cfg) => cfg,
            Self::AssetHubKusama(cfg) => cfg,
            Self::Terra(cfg) => cfg,
            Self::TerraClassic(cfg) => cfg,
            Self::ZeroG(cfg) => cfg,
            Self::Bittensor(cfg) => cfg,
            Self::Bera(cfg) => cfg,
            Self::Celo(cfg) => cfg,
            Self::Endurance(cfg) => cfg,
            Self::Movement(cfg) => cfg,
            Self::Kusama(cfg) => cfg,
            Self::Plume(cfg) => cfg,
            Self::Xrp(cfg) => cfg,
            Self::ZkSync(cfg) => cfg,
            Self::Metal(cfg) => cfg,
            Self::Cardano(cfg) => cfg,
            Self::Dymension(cfg) => cfg,
            Self::Axelar(cfg) => cfg,
            Self::Moonriver(cfg) => cfg,
            Self::Bob(cfg) => cfg,
            Self::Lumia(cfg) => cfg,
            Self::Iota(cfg) => cfg,
            Self::Ronin(cfg) => cfg,
            Self::BounceBit(cfg) => cfg,
            Self::Immutable(cfg) => cfg,
            Self::Fantom(cfg) => cfg,
            Self::Enjin(cfg) => cfg,
            Self::Band(cfg) => cfg,
            Self::Sei(cfg) => cfg,
            Self::Litecoin(cfg) => cfg,
            Self::Dogecoin(cfg) => cfg,
            Self::Mantle(cfg) => cfg,
            Self::Starknet(cfg) => cfg,
            Self::Morph(cfg) => cfg,
            Self::ArbitrumNova(cfg) => cfg,
            Self::Manta(cfg) => cfg,
            Self::Near(cfg) => cfg,
            Self::Lightning(cfg) => cfg,
            Self::Kcc(cfg) => cfg,
            Self::BitcoinSegWit(cfg) => cfg,
            Self::Fogo(cfg) => cfg,
            Self::Frax(cfg) => cfg,
            Self::Siacoin(cfg) => cfg,
            Self::VeChain(cfg) => cfg,
            Self::Theta(cfg) => cfg,
            Self::FetchAi(cfg) => cfg,
            Self::Arweave(cfg) => cfg,
            Self::Oasis(cfg) => cfg,
            Self::Cosmos(cfg) => cfg,
            Self::Fraxtal(cfg) => cfg,
            Self::Ravencoin(cfg) => cfg,
            Self::AssetHubPolkadot(cfg) => cfg,
            Self::Hedera(cfg) => cfg,
            Self::Algorand(cfg) => cfg,
            Self::Conflux(cfg) => cfg,
            Self::Init(cfg) => cfg,
            Self::Stellar(cfg) => cfg,
            Self::DigiByte(cfg) => cfg,
            Self::Nano(cfg) => cfg,
            Self::ECash(cfg) => cfg,
            Self::Syscoin(cfg) => cfg,
            Self::Kava(cfg) => cfg,
            Self::IoTeX(cfg) => cfg,
            Self::InternetComputer(cfg) => cfg,
            Self::Acala(cfg) => cfg,
            Self::FitFi(cfg) => cfg,
            Self::Stable(cfg) => cfg,
            Self::Wemix(cfg) => cfg,
            Self::Filecoin(cfg) => cfg,
            Self::Waves(cfg) => cfg,
            Self::Neutron(cfg) => cfg,
            Self::Merlin(cfg) => cfg,
            Self::Aurora(cfg) => cfg,
            Self::Nem(cfg) => cfg,
            Self::Skale(cfg) => cfg,
            Self::Solar(cfg) => cfg,
            Self::Nillion(cfg) => cfg,
            Self::Elastos(cfg) => cfg,
            Self::HyperEVM(cfg) => cfg,
            Self::Klaytn(cfg) => cfg,
            Self::Plasma(cfg) => cfg,
            Self::Zilliqa(cfg) => cfg,
            Self::SyscoinRollux(cfg) => cfg,
            Self::Injective(cfg) => cfg,
            Self::Thorchain(cfg) => cfg,
            Self::Sapphire(cfg) => cfg,
            Self::Zcash(cfg) => cfg,
            Self::Klever(cfg) => cfg,
            Self::Wax(cfg) => cfg,
            Self::Kaia(cfg) => cfg,
            Self::MantaAtlantic(cfg) => cfg,
            Self::ZigChain(cfg) => cfg,
            Self::Aptos(cfg) => cfg,
            Self::Chromia(cfg) => cfg,
            Self::Tanssi(cfg) => cfg,
            Self::MilkyWay(cfg) => cfg,
            Self::Flow(cfg) => cfg,
            Self::Qtum(cfg) => cfg,
            Self::VSystems(cfg) => cfg,
            Self::Beldex(cfg) => cfg,
            Self::Secret(cfg) => cfg,
            Self::Astar(cfg) => cfg,
            Self::Supra(cfg) => cfg,
            Self::Canton(cfg) => cfg,
            Self::Oort(cfg) => cfg,
            Self::Matrix(cfg) => cfg,
            Self::Xion(cfg) => cfg,
            Self::Xfi(cfg) => cfg,
            Self::U2U(cfg) => cfg,
            Self::Mintlayer(cfg) => cfg,
            Self::Xai(cfg) => cfg,
            Self::SmartChain(cfg) => cfg,
            Self::Meter(cfg) => cfg,
            Self::MeterGovernance(cfg) => cfg,
            Self::MapProtocol(cfg) => cfg,
            Self::Beam(cfg) => cfg,
            Self::Bitgert(cfg) => cfg,
            Self::Hype(cfg) => cfg,
            Self::Pivx(cfg) => cfg,
            Self::EthereumPoW(cfg) => cfg,
            Self::Oraichain(cfg) => cfg,
            Self::Namada(cfg) => cfg,
            Self::MantraChain(cfg) => cfg,
            Self::Shibarium(cfg) => cfg,
            Self::Tezos(cfg) => cfg,
            Self::Etherlink(cfg) => cfg,
            Self::Zircuit(cfg) => cfg,
            Self::Telos(cfg) => cfg,
            Self::UnicornUltraSolaris(cfg) => cfg,
            Self::Analog(cfg) => cfg,
            Self::Vana(cfg) => cfg,
            Self::Swell(cfg) => cfg,
            Self::Aleo(cfg) => cfg,
            Self::Flare(cfg) => cfg,
            Self::Camp(cfg) => cfg,
            Self::Venom(cfg) => cfg,
            Self::Bitshares(cfg) => cfg,
            Self::Hydragon(cfg) => cfg,
            Self::Sonic(cfg) => cfg,
            Self::NewChain(cfg) => cfg,
            Self::Casper(cfg) => cfg,
            Self::Hive(cfg) => cfg,
            Self::Octa(cfg) => cfg,
            Self::Shentu(cfg) => cfg,
            Self::Lukso(cfg) => cfg,
            Self::Nibiru(cfg) => cfg,
            Self::Osmosis(cfg) => cfg,
            Self::Tbc(cfg) => cfg,
            Self::Electroneum(cfg) => cfg,
            Self::Iron(cfg) => cfg,
            Self::Fio(cfg) => cfg,
            Self::Radix(cfg) => cfg,
            Self::Cronos(cfg) => cfg,
            Self::Xna(cfg) => cfg,
            Self::Fractal(cfg) => cfg,
            Self::Ergo(cfg) => cfg,
            Self::Fuse(cfg) => cfg,
            Self::Vaulta(cfg) => cfg,
            Self::Shardeum(cfg) => cfg,
            Self::HashKey(cfg) => cfg,
            Self::StaFi(cfg) => cfg,
            Self::Peaq(cfg) => cfg,
            Self::Steem(cfg) => cfg,
            Self::Sophon(cfg) => cfg,
            Self::Polymesh(cfg) => cfg,
            Self::Numbers(cfg) => cfg,
            Self::Kaspa(cfg) => cfg,
            Self::Constellation(cfg) => cfg,
            Self::T3rn(cfg) => cfg,
            Self::BitcoinSV(cfg) => cfg,
            Self::Maverick(cfg) => cfg,
            Self::Monero(cfg) => cfg,
            Self::Mon(cfg) => cfg,
            Self::Ultima(cfg) => cfg,
            Self::GraphLinq(cfg) => cfg,
            Self::Irisnet(cfg) => cfg,
            Self::Stratis(cfg) => cfg,
            Self::Pocket(cfg) => cfg,
            Self::Aelf(cfg) => cfg,
            Self::Ark(cfg) => cfg,
            Self::Akash(cfg) => cfg,
            Self::Core(cfg) => cfg,
            Self::XLayer(cfg) => cfg,
            Self::Allora(cfg) => cfg,
            Self::Emyria(cfg) => cfg,
            Self::EthereumClassic(cfg) => cfg,
            Self::Proton(cfg) => cfg,
            Self::Avail(cfg) => cfg,
            Self::Kub(cfg) => cfg,
            Self::ABCore(cfg) => cfg,
            Self::Humanode(cfg) => cfg,
            Self::Dynex(cfg) => cfg,
            Self::Saga(cfg) => cfg,
            Self::Oasys(cfg) => cfg,
            Self::Wanchain(cfg) => cfg,
            Self::Zelcash(cfg) => cfg,
            Self::Luckycoin(cfg) => cfg,
            Self::Lamina1(cfg) => cfg,
            Self::ZkVerify(cfg) => cfg,
            Self::Nervos(cfg) => cfg,
            Self::Blast(cfg) => cfg,
            Self::AlephZero(cfg) => cfg,
            Self::Somnia(cfg) => cfg,
        }
    }

    pub fn create_test() -> Network {
        Network::Bitcoin(NetworkConfig {
            name: "TestNet".to_string(),
            full_name: "TestNetwork".to_string(),
            coin_name: "TestNet".to_string(),
            withdraw_fee: None,
            contract_address: None,
            memo: None,
            deposit_address: None,
        })
    }
}
