refresh_rate: 30 seconds

appenders:
  errors:
    kind: rolling_file
    path: "logs/error/error.log"
    encoder:
      pattern: "{d} {l} {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 50 mb
      roller:
        kind: fixed_window
        pattern: "logs/error/errors.{}.log"
        base: 1
        count: 5

  unknown_networks:
    kind: rolling_file
    path: "logs/network/unknown_networks.log"
    encoder:
      pattern: "{d} {l} {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 10 mb  # Маленький, т.к. только ошибки парсинга
      roller:
        kind: fixed_window
        pattern: "logs/network/unknown_networks.{}.log"
        base: 1
        count: 3
  debugs:                     # Добавляем
    kind: rolling_file
    path: "logs/debug/debug.log"
    encoder:
      pattern: "{d} {l} {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 100 mb
      roller:
        kind: fixed_window
        pattern: "logs/debug/debug.{}.log"
        base: 1
        count: 10
  infos:
    kind: rolling_file
    path: "logs/info/info.log"        # Отдельный файл
    encoder:
      pattern: "{d} {l} - {m}{n}"    # Без уровня, т.к. только info
    policy:
      trigger:
        kind: size
        limit: 100 mb
      roller:
        kind: fixed_window
        pattern: "logs/info/info.{}.log"
        base: 1
        count: 10
loggers:
  unknown_networks_module:           # Для модуля парсинга сетей
    level: error            # ТОЛЬКО ошибки
    appenders:
      - unknown_networks    # В отдельный файл
    additive: false
  debug_module:               # Добавляем логгер для дебага
    level: debug
    appenders:
      - debugs
    additive: false
  info_module:
    level: info
    appenders:
      - infos
    additive: false

root:
  level: warn              # Общий уровень
  appenders:
    - errors               # Все ошибки сюда