pub const USDT_LIMIT: f64 = 1000.0;
pub const PAIRS_PER_THREAD: usize = 15;
pub const EXCHANGES_PER_TICKER_THREAD: usize = 4;
pub const QUOTE_LIST: &[&'static str] = &["USDT"];
pub const REQUIRED_SPREAD_PERCENT: f64 = 0.4;
pub const HTTP_MAX_POOL_IDLE_PER_HOST: usize = 20;
pub const HTTP_RETRY_AFTER_MILLIS: u64 = 300;

pub const GLOBAL_HTTP_TIMEOUT_SECS: u64 = 2;

// BINANCE REQUEST TIMEOUTS
pub const BINANCE_NETWORKS_HTTP_TIMEOUT_SECONDS: u64 = 5;

// BITGET REQUEST TIMEOUTS
pub const BITGET_MARGIN_INFO_HTTP_TIMEOUT_SECONDS: u64 = 5;

// GATE.IO REQUEST TIMEOUTS
pub const GATE_MARGIN_INFO_HTTP_TIMEOUT_SECONDS: u64 = 5;
pub const GATE_TICKERS_HTTP_TIMEOUT_SECONDS: u64 = 10;

// MEXC REQUEST TIMEOUTS
pub const MEXC_NETWORKS_HTTP_TIMEOUT_SECONDS: u64 = 5;

// HUOBI REQUEST TIMEOUTS
pub const HUOBI_TICKERS_HTTP_TIMEOUT_SECONDS: u64 = 10;
pub const HUOBI_MARGIN_INFO_HTTP_TIMEOUT_SECONDS: u64 = 5;
