pub const NAME: &str = "Gate.io";
pub const API_KEY: &str = "58fc3d2e64025e4d5a40a6a788beb958";
pub const SECRET_KEY: &str = "580d453127a78ce725bc1f83917ca50a347684e3f749f896a1ab55c6f05d89d1";
pub const BASE_URL: &str = "https://api.gateio.ws/api/v4";

pub const EXCLUDED_PAIRS: &[&str] = &[
    "KOGE_USDT",
    "VKHYPE_USDT",
    "KAU_USDT",
    "KAG_USDT",
    "ZEC_USDT",
    "IBERA_USDT",
    "ECOREAL_USDT",
    "WAVAX_USDT",
    "OUSG_USDT",
    "BCAP_USDT",
    "META_USDT",
    "ZANO_USDT",
    "XSO_USDT",
    "SAGE_USDT",
    "MSHD_USDT",
    "KTA_USDT",
    "OHM_USDT",
    "MAG7.SSI_USDT",
    "TEL_USDT",
    "RAIL_USDT",
    "REKT_USDT",
    "AGENTFUN_USDT",
    "HASH_USDT",
    "XMR_USDT",
    "EOS_USDT",
    "METH_USDT",
    "BORG_USDT",
    "DASH_USDT",
    "CMETH_USDT",
    "ATONE_USDT",
    "TDCCP_USDT",
    "CONSCIOUS_USDT",
    "SN115_USDT",
    "TIBBIR_USDT",
    "TBTC_USDT",
    "APEX_USDT",
    "MGG_USDT",
    "ZBZN_USDT",
    "NXM_USDT",
    "ZEN_USDT",
    "AXL_USDT",
    "SENA_USDT",
];
