pub const NAME: &str = "Kucoin";
// pub const API_KEY: &str = "68f5efbdf9a9a300014c0706";
// pub const SECRET_KEY: &str = "d4a61c1d-fa45-49ce-a1d7-6016bf07b93f";
pub const BASE_URL: &str = "https://api.kucoin.com";
pub const PASSPHRASE: &str = "kotyashki322";
pub const SECRET_KEY: &str = "91dd6923-cf6b-4570-a9aa-347e10fb660e";
pub const API_KEY: &str = "68f5fe88fa2aaa0001e52331";
pub const EXCLUDED_PAIRS: &[&str] = &[
    "LEO_USDT",
    "BSV_USDT",
    "TBTC_USDT",
    "NEXO_USDT",
    "FTN_USDT",
    "GALA_USDT",
    "AB_USDT",
    "OUSG_USDT",
    "METH_USDT",
    "COAI_USDT",
    "CMETH_USDT",
    "BORG_USDT",
    "MYX_USDT",
    "GNO_USDT",
    "WAVAX_USDT",
    "APEPE_USDT",
    "BCAP_USDT",
    "REAL_USDT",
    "IBERA_USDT",
    "ECOREAL_USDT",
    "KAG_USDT",
    "LION_USDT",
    "VVS_USDT",
    "ALEO_USDT",
    "KAU_USDT",
    "QUBIC_USDT",
    "ZIG_USDT",
    "TRIBE_USDT",
    "VKHYPE_USDT",
    "KOGE_USDT",
    "RON_USDT",
    "EOS_USDT",
    "OG_USDT",
    "DOG_USDT",
    "ARK_USDT",
    "OHM_USDT",
    "META_USDT",
    "ZANO_USDT",
    "NXM_USDT",
    "SVL_USDT",
    "M_USDT",
    "CONSCIOUS_USDT",
    "MAG7.SSI_USDT",
    "SN115_USDT",
    "GHO_USDT",
    "CORE_USDT",
    "B_USDT",
    "ULTIMA_USDT",
    "MGG_USDT",
    "RAIL_USDT",
    "XSO_USDT",
    "APEX_USDT",
    "METAL_USDT",
    "AGENTFUN_USDT",
    "KTA_USDT",
    "TDCCP_USDT",
    "HASH_USDT",
    "SAGE_USDT",
    "BEAM_USDT",
    "TIBBIR_USDT",
    "SENA_USDT",
    "AIC_USDT",
    "FLUID_USDT",
    "ATONE_USDT",
    "FORM_USDT",
    "MSHD_USDT",
    "AXL_USDT",
    "UDS_USDT",
    "ZBZN_USDT",
    "SOSO_USDT",
];
