pub const NAME: &str = "Mexc";
pub const API_KEY: &str = "mx0vglN6BUqTW2bG79";
pub const SECRET_KEY: &str = "e624619370d641f3a97b360d51975f87";
pub const BASE_URL: &str = "https://api.mexc.com";
pub const EXCLUDED_PAIRS: &[&str] = &[
    "LEO_USDT",
    "TBTC_USDT",
    "BONK_USDT",
    "THETA_USDT",
    "OUSG_USDT",
    "METH_USDT",
    "BORG_USDT",
    "CMETH_USDT",
    "KOGE_USDT",
    "TRIBE_USDT",
    "VKHYPE_USDT",
    "VVS_USDT",
    "ECOREAL_USDT",
    "KAG_USDT",
    "AIOZ_USDT",
    "IBERA_USDT",
    "BCAP_USDT",
    "WAVAX_USDT",
    "GLM_USDT",
    "META_USDT",
    "KAU_USDT",
    "EOS_USDT",
    "LION_USDT",
    "OHM_USDT",
    "NXM_USDT",
    "GAS_USDT",
    "CONSCIOUS_USDT",
    "MAG7.SSI_USDT",
    "XSO_USDT",
    "MGG_USDT",
    "SAGE_USDT",
    "AGENTFUN_USDT",
    "AKT_USDT",
    "SUPER_USDT",
    "AXL_USDT",
    "MSHD_USDT",
    "TDCCP_USDT",
    "ATONE_USDT",
    "ZBZN_USDT",
    "REKT_USDT",
    "HASH_USDT",
    "GHO_USDT",
    "SN115_USDT",
    "BRETT_USDT",
    "SENA_USDT",
];
